table Trend
	lineageTag: 8533f102-12f6-4340-8165-3dc4c97732ca

	column Brand
		dataType: string
		lineageTag: 4c1ce2d5-bb3b-4f3e-bf72-33157d61bc65
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column 'Monthly target'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6b5f0602-4a01-4000-9a25-65e98fcf9d90
		summarizeBy: none
		sourceColumn: Monthly target

		annotation SummarizationSetBy = Automatic

	partition Trend = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WctRTcEksKc1V0lEyNDMAA6VYnWgl5/y8kvzifJCwBZKwY0pZal5JaVGqQnh+UXYxUNrIACYdCwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Brand = _t, #"Monthly target" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Brand", type text}, {"Monthly target", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

